//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v11.1.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------







export interface AssetLink {
    entityName: string;
    recordId: number;
    assetId: number;
    createdAt: Date;
    updatedAt: Date;
    id: number;
}

export interface Asset {
    path: string;
    url: string;
    name: string;
    title: string;
    size: number;
    type: string;
    metadata: { [key: string]: any; };
    createdBy: string;
    createdAt: Date;
    updatedAt: Date;
    id: number;
    linkCount: number;
    links: AssetLink[] | undefined;
}