//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v11.1.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------







export enum TaskStatus {
    Init = "init",
    InProgress = "inProgress",
    Finished = "finished",
    Failed = "failed",
}

export enum TaskType {
    Default = "default",
    Export = "export",
    Import = "import",
}

export interface SystemTask {
    taskStatus: TaskStatus;
    type: TaskType;
    createdBy: string;
    id: number;
    progress: number;
    createdAt: Date;
    updatedAt: Date;
}