//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v11.1.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------







export interface MenuItem {
    icon: string;
    label: string;
    url: string;
    isHref: boolean;
}

export interface Menu {
    name: string;
    menuItems: MenuItem[];
}